@startuml context
!define C4P https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/refs/heads/master/C4_Context.puml
!includeurl C4P

Person(user, "Пользователь", "Пользователь умного дома")
System_Ext(module, "Система отопления", "Установленные датчики и реле умного дома")
System(server, "Система умный дом", "Позволяет пользователям удаленно управлять отоплением")

Rel(server, module, "Получает данные о температуре, управляет отоплением")
Rel(user, server, "Управляет отоплением, просматривает температуру")
Rel(user, module, "Подключает")
@enduml
